### ISSUE TITLE
Prepare for ~50k folders/files in git and web hosting with gh-pages

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#2]
https://stackoverflow.com/questions/38768454/repository-size-limits-for-github-com
https://www.monperrus.net/martin/one-million-files-on-git-and-github

Will it really be possible to serve the webpage with gh-pages?

**Comment by jalbertbowden** [comment]
I'm not sure the file size limit is going to be an issue; actually I'm pretty sure that it will not.
As for number of files in a directory, I don't think this will be an issue either because we are scattering them around under the date variables directories.
I could be wrong here, but my experience tells me this is going to be just fine.
I'm going to fiddle with it tonight a little bit, and maybe we'll get some idea of what it will be like.
Or rather, lets try and see what happens.

**Comment by philshem** [comment]
one thing will be to have all the folders for years not in a top level directory, otherwise will look messy in git.

file path:
 
     dates/1980/06/30

**Comment by philshem** [comment]
seems to work on gh-pages with no lag

https://co2birthdate.github.io/website/dates/1900/06/01/
